#lang racket/base
;; ---------------------------------------------------------------------------------------------------

(require "private/locus-local.rkt")
(provide (rename-out
          [locus place]
          [locus/context place/context]
          [locus-running? place-running?]
          [locus-exit-code place-exit-code]
          [locus-kill place-kill]
          [locus-enabled? place-enabled?]
          [dynamic-locus dynamic-place]
          [locus-dead-evt place-dead-evt]
          [locus-wait place-wait]
          [locus? place?]
          [locus-channel-put/get place-channel-put/get]
          [locus-message-allowed? place-message-allowed?]
          [locus-channel? place-channel?]
          [locus-channel-put place-channel-put]
          [locus-channel-get place-channel-get]))
